services:
  windows-builder:
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - MODE=${MODE:-compile-onefile}
      - MAINARGS=$MAINARGS
      - PYINSTALLERARGS=$PYINSTALLERARGS
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../docker:/app/docker:ro
      #- /home/giswarm/tmp/MeshCNN:/app/project:ro
      - ../project:/app/project:ro
      - ../build:/app/build:rwo
      - ../runtime:/app/runtime:rwo
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:rw
      - installation_state:/app/state
      - wine:/root/.wine
    network_mode: host
    working_dir: /app
    entrypoint: ["/app/docker/entrypoint.sh"]
    command: []
    stdin_open: true
    tty: true

volumes:
  installation_state:
  wine:

